<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class CollaboratorService extends \App\Entity\CollaboratorService implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\CollaboratorService' . "\0" . 'id', '' . "\0" . 'App\\Entity\\CollaboratorService' . "\0" . 'code', '' . "\0" . 'App\\Entity\\CollaboratorService' . "\0" . 'description', '' . "\0" . 'App\\Entity\\CollaboratorService' . "\0" . 'craneServices', '' . "\0" . 'App\\Entity\\CollaboratorService' . "\0" . 'interventions', '' . "\0" . 'App\\Entity\\CollaboratorService' . "\0" . 'requestCraneCollaboratorServices', '' . "\0" . 'App\\Entity\\CollaboratorService' . "\0" . 'branchOfficeServices', '' . "\0" . 'App\\Entity\\CollaboratorService' . "\0" . 'activities', '' . "\0" . 'App\\Entity\\CollaboratorService' . "\0" . 'budgets'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\CollaboratorService' . "\0" . 'id', '' . "\0" . 'App\\Entity\\CollaboratorService' . "\0" . 'code', '' . "\0" . 'App\\Entity\\CollaboratorService' . "\0" . 'description', '' . "\0" . 'App\\Entity\\CollaboratorService' . "\0" . 'craneServices', '' . "\0" . 'App\\Entity\\CollaboratorService' . "\0" . 'interventions', '' . "\0" . 'App\\Entity\\CollaboratorService' . "\0" . 'requestCraneCollaboratorServices', '' . "\0" . 'App\\Entity\\CollaboratorService' . "\0" . 'branchOfficeServices', '' . "\0" . 'App\\Entity\\CollaboratorService' . "\0" . 'activities', '' . "\0" . 'App\\Entity\\CollaboratorService' . "\0" . 'budgets'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (CollaboratorService $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getCode(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCode', []);

        return parent::getCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setCode(string $code): \App\Entity\CollaboratorService
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCode', [$code]);

        return parent::setCode($code);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription(string $description): \App\Entity\CollaboratorService
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getCraneServices(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCraneServices', []);

        return parent::getCraneServices();
    }

    /**
     * {@inheritDoc}
     */
    public function addCraneService(\App\Entity\CraneService $craneService): \App\Entity\CollaboratorService
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCraneService', [$craneService]);

        return parent::addCraneService($craneService);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCraneService(\App\Entity\CraneService $craneService): \App\Entity\CollaboratorService
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCraneService', [$craneService]);

        return parent::removeCraneService($craneService);
    }

    /**
     * {@inheritDoc}
     */
    public function getInterventions(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInterventions', []);

        return parent::getInterventions();
    }

    /**
     * {@inheritDoc}
     */
    public function addIntervention(\App\Entity\Intervention $intervention): \App\Entity\CollaboratorService
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addIntervention', [$intervention]);

        return parent::addIntervention($intervention);
    }

    /**
     * {@inheritDoc}
     */
    public function removeIntervention(\App\Entity\Intervention $intervention): \App\Entity\CollaboratorService
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeIntervention', [$intervention]);

        return parent::removeIntervention($intervention);
    }

    /**
     * {@inheritDoc}
     */
    public function getRequestCraneCollaboratorServices(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRequestCraneCollaboratorServices', []);

        return parent::getRequestCraneCollaboratorServices();
    }

    /**
     * {@inheritDoc}
     */
    public function addRequestCraneCollaboratorService(\App\Entity\RequestCraneCollaboratorService $requestCraneCollaboratorService): \App\Entity\CollaboratorService
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addRequestCraneCollaboratorService', [$requestCraneCollaboratorService]);

        return parent::addRequestCraneCollaboratorService($requestCraneCollaboratorService);
    }

    /**
     * {@inheritDoc}
     */
    public function removeRequestCraneCollaboratorService(\App\Entity\RequestCraneCollaboratorService $requestCraneCollaboratorService): \App\Entity\CollaboratorService
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeRequestCraneCollaboratorService', [$requestCraneCollaboratorService]);

        return parent::removeRequestCraneCollaboratorService($requestCraneCollaboratorService);
    }

    /**
     * {@inheritDoc}
     */
    public function getBranchOfficeServices(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBranchOfficeServices', []);

        return parent::getBranchOfficeServices();
    }

    /**
     * {@inheritDoc}
     */
    public function addBranchOfficeService(\App\Entity\BranchOfficeService $branchOfficeService): \App\Entity\CollaboratorService
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addBranchOfficeService', [$branchOfficeService]);

        return parent::addBranchOfficeService($branchOfficeService);
    }

    /**
     * {@inheritDoc}
     */
    public function removeBranchOfficeService(\App\Entity\BranchOfficeService $branchOfficeService): \App\Entity\CollaboratorService
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeBranchOfficeService', [$branchOfficeService]);

        return parent::removeBranchOfficeService($branchOfficeService);
    }

    /**
     * {@inheritDoc}
     */
    public function getActivities(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActivities', []);

        return parent::getActivities();
    }

    /**
     * {@inheritDoc}
     */
    public function addActivity(\App\Entity\Activity $activity): \App\Entity\CollaboratorService
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addActivity', [$activity]);

        return parent::addActivity($activity);
    }

    /**
     * {@inheritDoc}
     */
    public function removeActivity(\App\Entity\Activity $activity): \App\Entity\CollaboratorService
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeActivity', [$activity]);

        return parent::removeActivity($activity);
    }

    /**
     * {@inheritDoc}
     */
    public function getBudgets(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBudgets', []);

        return parent::getBudgets();
    }

    /**
     * {@inheritDoc}
     */
    public function addBudget(\App\Entity\Budget $budget): \App\Entity\CollaboratorService
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addBudget', [$budget]);

        return parent::addBudget($budget);
    }

    /**
     * {@inheritDoc}
     */
    public function removeBudget(\App\Entity\Budget $budget): \App\Entity\CollaboratorService
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeBudget', [$budget]);

        return parent::removeBudget($budget);
    }

}
