<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Crane extends \App\Entity\Crane implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Crane' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Crane' . "\0" . 'plate', '' . "\0" . 'App\\Entity\\Crane' . "\0" . 'openFrom', '' . "\0" . 'App\\Entity\\Crane' . "\0" . 'openTo', '' . "\0" . 'App\\Entity\\Crane' . "\0" . 'workingDays', '' . "\0" . 'App\\Entity\\Crane' . "\0" . 'creationDate', '' . "\0" . 'App\\Entity\\Crane' . "\0" . 'deletionDate', '' . "\0" . 'App\\Entity\\Crane' . "\0" . 'registrationDate', '' . "\0" . 'App\\Entity\\Crane' . "\0" . 'lastSyncDate', '' . "\0" . 'App\\Entity\\Crane' . "\0" . 'comments', '' . "\0" . 'App\\Entity\\Crane' . "\0" . 'craneServices', '' . "\0" . 'App\\Entity\\Crane' . "\0" . 'craneStatus', '' . "\0" . 'App\\Entity\\Crane' . "\0" . 'craneType', '' . "\0" . 'App\\Entity\\Crane' . "\0" . 'brand', '' . "\0" . 'App\\Entity\\Crane' . "\0" . 'model', '' . "\0" . 'App\\Entity\\Crane' . "\0" . 'availabilityStatus', '' . "\0" . 'App\\Entity\\Crane' . "\0" . 'interventions', '' . "\0" . 'App\\Entity\\Crane' . "\0" . 'attachments', '' . "\0" . 'App\\Entity\\Crane' . "\0" . 'branchOfficeCranes', '' . "\0" . 'App\\Entity\\Crane' . "\0" . 'operators', '' . "\0" . 'App\\Entity\\Crane' . "\0" . 'code', '' . "\0" . 'App\\Entity\\Crane' . "\0" . 'workingHours', '' . "\0" . 'App\\Entity\\Crane' . "\0" . 'managementType', '' . "\0" . 'App\\Entity\\Crane' . "\0" . 'collaborator', '' . "\0" . 'App\\Entity\\Crane' . "\0" . 'labeledType', '' . "\0" . 'App\\Entity\\Crane' . "\0" . 'reference', '' . "\0" . 'App\\Entity\\Crane' . "\0" . 'operatorAvailableCranes'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Crane' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Crane' . "\0" . 'plate', '' . "\0" . 'App\\Entity\\Crane' . "\0" . 'openFrom', '' . "\0" . 'App\\Entity\\Crane' . "\0" . 'openTo', '' . "\0" . 'App\\Entity\\Crane' . "\0" . 'workingDays', '' . "\0" . 'App\\Entity\\Crane' . "\0" . 'creationDate', '' . "\0" . 'App\\Entity\\Crane' . "\0" . 'deletionDate', '' . "\0" . 'App\\Entity\\Crane' . "\0" . 'registrationDate', '' . "\0" . 'App\\Entity\\Crane' . "\0" . 'lastSyncDate', '' . "\0" . 'App\\Entity\\Crane' . "\0" . 'comments', '' . "\0" . 'App\\Entity\\Crane' . "\0" . 'craneServices', '' . "\0" . 'App\\Entity\\Crane' . "\0" . 'craneStatus', '' . "\0" . 'App\\Entity\\Crane' . "\0" . 'craneType', '' . "\0" . 'App\\Entity\\Crane' . "\0" . 'brand', '' . "\0" . 'App\\Entity\\Crane' . "\0" . 'model', '' . "\0" . 'App\\Entity\\Crane' . "\0" . 'availabilityStatus', '' . "\0" . 'App\\Entity\\Crane' . "\0" . 'interventions', '' . "\0" . 'App\\Entity\\Crane' . "\0" . 'attachments', '' . "\0" . 'App\\Entity\\Crane' . "\0" . 'branchOfficeCranes', '' . "\0" . 'App\\Entity\\Crane' . "\0" . 'operators', '' . "\0" . 'App\\Entity\\Crane' . "\0" . 'code', '' . "\0" . 'App\\Entity\\Crane' . "\0" . 'workingHours', '' . "\0" . 'App\\Entity\\Crane' . "\0" . 'managementType', '' . "\0" . 'App\\Entity\\Crane' . "\0" . 'collaborator', '' . "\0" . 'App\\Entity\\Crane' . "\0" . 'labeledType', '' . "\0" . 'App\\Entity\\Crane' . "\0" . 'reference', '' . "\0" . 'App\\Entity\\Crane' . "\0" . 'operatorAvailableCranes'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Crane $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getPlate(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPlate', []);

        return parent::getPlate();
    }

    /**
     * {@inheritDoc}
     */
    public function setPlate(?string $plate): \App\Entity\Crane
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPlate', [$plate]);

        return parent::setPlate($plate);
    }

    /**
     * {@inheritDoc}
     */
    public function getOpenFrom(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOpenFrom', []);

        return parent::getOpenFrom();
    }

    /**
     * {@inheritDoc}
     */
    public function setOpenFrom(?string $openFrom): \App\Entity\Crane
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOpenFrom', [$openFrom]);

        return parent::setOpenFrom($openFrom);
    }

    /**
     * {@inheritDoc}
     */
    public function getOpenTo(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOpenTo', []);

        return parent::getOpenTo();
    }

    /**
     * {@inheritDoc}
     */
    public function setOpenTo(?string $openTo): \App\Entity\Crane
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOpenTo', [$openTo]);

        return parent::setOpenTo($openTo);
    }

    /**
     * {@inheritDoc}
     */
    public function getWorkingDays(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWorkingDays', []);

        return parent::getWorkingDays();
    }

    /**
     * {@inheritDoc}
     */
    public function setWorkingDays(?string $workingDays): \App\Entity\Crane
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWorkingDays', [$workingDays]);

        return parent::setWorkingDays($workingDays);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreationDate(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreationDate', []);

        return parent::getCreationDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreationDate(?\DateTimeInterface $creationDate): \App\Entity\Crane
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreationDate', [$creationDate]);

        return parent::setCreationDate($creationDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getDeletionDate(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDeletionDate', []);

        return parent::getDeletionDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setDeletionDate(?\DateTimeInterface $deletionDate): \App\Entity\Crane
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDeletionDate', [$deletionDate]);

        return parent::setDeletionDate($deletionDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getRegistrationDate(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRegistrationDate', []);

        return parent::getRegistrationDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setRegistrationDate(?\DateTimeInterface $registrationDate): \App\Entity\Crane
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRegistrationDate', [$registrationDate]);

        return parent::setRegistrationDate($registrationDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getLastSyncDate(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLastSyncDate', []);

        return parent::getLastSyncDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setLastSyncDate(?\DateTimeInterface $lastSyncDate): \App\Entity\Crane
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLastSyncDate', [$lastSyncDate]);

        return parent::setLastSyncDate($lastSyncDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getComments(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getComments', []);

        return parent::getComments();
    }

    /**
     * {@inheritDoc}
     */
    public function setComments(?string $comments): \App\Entity\Crane
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setComments', [$comments]);

        return parent::setComments($comments);
    }

    /**
     * {@inheritDoc}
     */
    public function getCraneServices(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCraneServices', []);

        return parent::getCraneServices();
    }

    /**
     * {@inheritDoc}
     */
    public function addCraneService(\App\Entity\CraneService $craneService): \App\Entity\Crane
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCraneService', [$craneService]);

        return parent::addCraneService($craneService);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCraneService(\App\Entity\CraneService $craneService): \App\Entity\Crane
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCraneService', [$craneService]);

        return parent::removeCraneService($craneService);
    }

    /**
     * {@inheritDoc}
     */
    public function getCraneStatus(): ?\App\Entity\CraneStatus
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCraneStatus', []);

        return parent::getCraneStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setCraneStatus(?\App\Entity\CraneStatus $craneStatus): \App\Entity\Crane
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCraneStatus', [$craneStatus]);

        return parent::setCraneStatus($craneStatus);
    }

    /**
     * {@inheritDoc}
     */
    public function getCraneType(): ?\App\Entity\CraneType
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCraneType', []);

        return parent::getCraneType();
    }

    /**
     * {@inheritDoc}
     */
    public function setCraneType(?\App\Entity\CraneType $craneType): \App\Entity\Crane
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCraneType', [$craneType]);

        return parent::setCraneType($craneType);
    }

    /**
     * {@inheritDoc}
     */
    public function getBrand(): ?\App\Entity\Brand
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBrand', []);

        return parent::getBrand();
    }

    /**
     * {@inheritDoc}
     */
    public function setBrand(?\App\Entity\Brand $brand): \App\Entity\Crane
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBrand', [$brand]);

        return parent::setBrand($brand);
    }

    /**
     * {@inheritDoc}
     */
    public function getModel(): ?\App\Entity\Model
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getModel', []);

        return parent::getModel();
    }

    /**
     * {@inheritDoc}
     */
    public function setModel(?\App\Entity\Model $model): \App\Entity\Crane
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setModel', [$model]);

        return parent::setModel($model);
    }

    /**
     * {@inheritDoc}
     */
    public function getAvailabilityStatus(): ?\App\Entity\AvailabilityStatus
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAvailabilityStatus', []);

        return parent::getAvailabilityStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setAvailabilityStatus(?\App\Entity\AvailabilityStatus $availabilityStatus): \App\Entity\Crane
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAvailabilityStatus', [$availabilityStatus]);

        return parent::setAvailabilityStatus($availabilityStatus);
    }

    /**
     * {@inheritDoc}
     */
    public function getInterventions(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInterventions', []);

        return parent::getInterventions();
    }

    /**
     * {@inheritDoc}
     */
    public function addIntervention(\App\Entity\Intervention $intervention): \App\Entity\Crane
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addIntervention', [$intervention]);

        return parent::addIntervention($intervention);
    }

    /**
     * {@inheritDoc}
     */
    public function removeIntervention(\App\Entity\Intervention $intervention): \App\Entity\Crane
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeIntervention', [$intervention]);

        return parent::removeIntervention($intervention);
    }

    /**
     * {@inheritDoc}
     */
    public function getAttachments(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAttachments', []);

        return parent::getAttachments();
    }

    /**
     * {@inheritDoc}
     */
    public function addAttachment(\App\Entity\Attachment $attachment): \App\Entity\Crane
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addAttachment', [$attachment]);

        return parent::addAttachment($attachment);
    }

    /**
     * {@inheritDoc}
     */
    public function removeAttachment(\App\Entity\Attachment $attachment): \App\Entity\Crane
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeAttachment', [$attachment]);

        return parent::removeAttachment($attachment);
    }

    /**
     * {@inheritDoc}
     */
    public function getBranchOfficeCranes(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBranchOfficeCranes', []);

        return parent::getBranchOfficeCranes();
    }

    /**
     * {@inheritDoc}
     */
    public function addBranchOfficeCrane(\App\Entity\BranchOfficeCrane $branchOfficeCrane): \App\Entity\Crane
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addBranchOfficeCrane', [$branchOfficeCrane]);

        return parent::addBranchOfficeCrane($branchOfficeCrane);
    }

    /**
     * {@inheritDoc}
     */
    public function removeBranchOfficeCrane(\App\Entity\BranchOfficeCrane $branchOfficeCrane): \App\Entity\Crane
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeBranchOfficeCrane', [$branchOfficeCrane]);

        return parent::removeBranchOfficeCrane($branchOfficeCrane);
    }

    /**
     * {@inheritDoc}
     */
    public function getOperators(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOperators', []);

        return parent::getOperators();
    }

    /**
     * {@inheritDoc}
     */
    public function addOperator(\App\Entity\Operator $operator): \App\Entity\Crane
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addOperator', [$operator]);

        return parent::addOperator($operator);
    }

    /**
     * {@inheritDoc}
     */
    public function removeOperator(\App\Entity\Operator $operator): \App\Entity\Crane
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeOperator', [$operator]);

        return parent::removeOperator($operator);
    }

    /**
     * {@inheritDoc}
     */
    public function getCode(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCode', []);

        return parent::getCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setCode(?string $code): \App\Entity\Crane
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCode', [$code]);

        return parent::setCode($code);
    }

    /**
     * {@inheritDoc}
     */
    public function getWorkingHours(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWorkingHours', []);

        return parent::getWorkingHours();
    }

    /**
     * {@inheritDoc}
     */
    public function addWorkingHour(\App\Entity\WorkingHours $workingHour): \App\Entity\Crane
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addWorkingHour', [$workingHour]);

        return parent::addWorkingHour($workingHour);
    }

    /**
     * {@inheritDoc}
     */
    public function removeWorkingHour(\App\Entity\WorkingHours $workingHour): \App\Entity\Crane
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeWorkingHour', [$workingHour]);

        return parent::removeWorkingHour($workingHour);
    }

    /**
     * {@inheritDoc}
     */
    public function getManagementType(): ?\App\Entity\CraneManagementType
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getManagementType', []);

        return parent::getManagementType();
    }

    /**
     * {@inheritDoc}
     */
    public function setManagementType(?\App\Entity\CraneManagementType $managementType): \App\Entity\Crane
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setManagementType', [$managementType]);

        return parent::setManagementType($managementType);
    }

    /**
     * {@inheritDoc}
     */
    public function getCollaborator(): ?\App\Entity\Collaborator
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCollaborator', []);

        return parent::getCollaborator();
    }

    /**
     * {@inheritDoc}
     */
    public function setCollaborator(?\App\Entity\Collaborator $collaborator): \App\Entity\Crane
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCollaborator', [$collaborator]);

        return parent::setCollaborator($collaborator);
    }

    /**
     * {@inheritDoc}
     */
    public function getLabeledType(): ?\App\Entity\LabeledType
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLabeledType', []);

        return parent::getLabeledType();
    }

    /**
     * {@inheritDoc}
     */
    public function setLabeledType(?\App\Entity\LabeledType $labeledType): \App\Entity\Crane
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLabeledType', [$labeledType]);

        return parent::setLabeledType($labeledType);
    }

    /**
     * {@inheritDoc}
     */
    public function getReference(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReference', []);

        return parent::getReference();
    }

    /**
     * {@inheritDoc}
     */
    public function setReference(?string $reference): \App\Entity\Crane
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReference', [$reference]);

        return parent::setReference($reference);
    }

    /**
     * {@inheritDoc}
     */
    public function getOperatorAvailableCranes(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOperatorAvailableCranes', []);

        return parent::getOperatorAvailableCranes();
    }

    /**
     * {@inheritDoc}
     */
    public function addOperatorAvailableCrane(\App\Entity\OperatorAvailableCranes $operatorAvailableCrane): \App\Entity\Crane
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addOperatorAvailableCrane', [$operatorAvailableCrane]);

        return parent::addOperatorAvailableCrane($operatorAvailableCrane);
    }

    /**
     * {@inheritDoc}
     */
    public function removeOperatorAvailableCrane(\App\Entity\OperatorAvailableCranes $operatorAvailableCrane): \App\Entity\Crane
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeOperatorAvailableCrane', [$operatorAvailableCrane]);

        return parent::removeOperatorAvailableCrane($operatorAvailableCrane);
    }

}
