<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Phase extends \App\Entity\Phase implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Phase' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Phase' . "\0" . 'code', '' . "\0" . 'App\\Entity\\Phase' . "\0" . 'description', '' . "\0" . 'App\\Entity\\Phase' . "\0" . 'interventions', '' . "\0" . 'App\\Entity\\Phase' . "\0" . 'phaseLogs', '' . "\0" . 'App\\Entity\\Phase' . "\0" . 'incidenceOfPhases', '' . "\0" . 'App\\Entity\\Phase' . "\0" . 'asiturCode', '' . "\0" . 'App\\Entity\\Phase' . "\0" . 'asiturDescription', '' . "\0" . 'App\\Entity\\Phase' . "\0" . 'previousPhase', '' . "\0" . 'App\\Entity\\Phase' . "\0" . 'phases'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Phase' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Phase' . "\0" . 'code', '' . "\0" . 'App\\Entity\\Phase' . "\0" . 'description', '' . "\0" . 'App\\Entity\\Phase' . "\0" . 'interventions', '' . "\0" . 'App\\Entity\\Phase' . "\0" . 'phaseLogs', '' . "\0" . 'App\\Entity\\Phase' . "\0" . 'incidenceOfPhases', '' . "\0" . 'App\\Entity\\Phase' . "\0" . 'asiturCode', '' . "\0" . 'App\\Entity\\Phase' . "\0" . 'asiturDescription', '' . "\0" . 'App\\Entity\\Phase' . "\0" . 'previousPhase', '' . "\0" . 'App\\Entity\\Phase' . "\0" . 'phases'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Phase $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getCode(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCode', []);

        return parent::getCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setCode(string $code): \App\Entity\Phase
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCode', [$code]);

        return parent::setCode($code);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription(string $description): \App\Entity\Phase
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getInterventions(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInterventions', []);

        return parent::getInterventions();
    }

    /**
     * {@inheritDoc}
     */
    public function addIntervention(\App\Entity\Intervention $intervention): \App\Entity\Phase
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addIntervention', [$intervention]);

        return parent::addIntervention($intervention);
    }

    /**
     * {@inheritDoc}
     */
    public function removeIntervention(\App\Entity\Intervention $intervention): \App\Entity\Phase
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeIntervention', [$intervention]);

        return parent::removeIntervention($intervention);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhaseLogs(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhaseLogs', []);

        return parent::getPhaseLogs();
    }

    /**
     * {@inheritDoc}
     */
    public function addPhaseLog(\App\Entity\PhaseLog $phaseLog): \App\Entity\Phase
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPhaseLog', [$phaseLog]);

        return parent::addPhaseLog($phaseLog);
    }

    /**
     * {@inheritDoc}
     */
    public function removePhaseLog(\App\Entity\PhaseLog $phaseLog): \App\Entity\Phase
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removePhaseLog', [$phaseLog]);

        return parent::removePhaseLog($phaseLog);
    }

    /**
     * {@inheritDoc}
     */
    public function getIncidenceOfPhases(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIncidenceOfPhases', []);

        return parent::getIncidenceOfPhases();
    }

    /**
     * {@inheritDoc}
     */
    public function addIncidenceOfPhase(\App\Entity\IncidenceOfPhase $incidenceOfPhase): \App\Entity\Phase
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addIncidenceOfPhase', [$incidenceOfPhase]);

        return parent::addIncidenceOfPhase($incidenceOfPhase);
    }

    /**
     * {@inheritDoc}
     */
    public function removeIncidenceOfPhase(\App\Entity\IncidenceOfPhase $incidenceOfPhase): \App\Entity\Phase
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeIncidenceOfPhase', [$incidenceOfPhase]);

        return parent::removeIncidenceOfPhase($incidenceOfPhase);
    }

    /**
     * {@inheritDoc}
     */
    public function getAsiturCode(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAsiturCode', []);

        return parent::getAsiturCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setAsiturCode(?string $asiturCode): \App\Entity\Phase
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAsiturCode', [$asiturCode]);

        return parent::setAsiturCode($asiturCode);
    }

    /**
     * {@inheritDoc}
     */
    public function getAsiturDescription(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAsiturDescription', []);

        return parent::getAsiturDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setAsiturDescription(?string $asiturDescription): \App\Entity\Phase
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAsiturDescription', [$asiturDescription]);

        return parent::setAsiturDescription($asiturDescription);
    }

    /**
     * {@inheritDoc}
     */
    public function getPreviousPhase(): ?\App\Entity\Phase
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPreviousPhase', []);

        return parent::getPreviousPhase();
    }

    /**
     * {@inheritDoc}
     */
    public function setPreviousPhase(?\App\Entity\Phase $previousPhase): \App\Entity\Phase
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPreviousPhase', [$previousPhase]);

        return parent::setPreviousPhase($previousPhase);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhases(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhases', []);

        return parent::getPhases();
    }

    /**
     * {@inheritDoc}
     */
    public function addPhase(\App\Entity\Phase $phase): \App\Entity\Phase
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPhase', [$phase]);

        return parent::addPhase($phase);
    }

    /**
     * {@inheritDoc}
     */
    public function removePhase(\App\Entity\Phase $phase): \App\Entity\Phase
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removePhase', [$phase]);

        return parent::removePhase($phase);
    }

}
