<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Collaborator extends \App\Entity\Collaborator implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Collaborator' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Collaborator' . "\0" . 'name', '' . "\0" . 'App\\Entity\\Collaborator' . "\0" . 'nif', '' . "\0" . 'App\\Entity\\Collaborator' . "\0" . 'lastSyncDate', '' . "\0" . 'App\\Entity\\Collaborator' . "\0" . 'webhookTypes', '' . "\0" . 'App\\Entity\\Collaborator' . "\0" . 'webhooks', '' . "\0" . 'App\\Entity\\Collaborator' . "\0" . 'interventions', '' . "\0" . 'App\\Entity\\Collaborator' . "\0" . 'interventionsCreated', '' . "\0" . 'App\\Entity\\Collaborator' . "\0" . 'branchOffices', '' . "\0" . 'App\\Entity\\Collaborator' . "\0" . 'collaboratorUsers', '' . "\0" . 'App\\Entity\\Collaborator' . "\0" . 'code', '' . "\0" . 'App\\Entity\\Collaborator' . "\0" . 'dateFormat', '' . "\0" . 'App\\Entity\\Collaborator' . "\0" . 'operators', '' . "\0" . 'App\\Entity\\Collaborator' . "\0" . 'cranes', '' . "\0" . 'App\\Entity\\Collaborator' . "\0" . 'email', '' . "\0" . 'App\\Entity\\Collaborator' . "\0" . 'dateFormatSql', '' . "\0" . 'App\\Entity\\Collaborator' . "\0" . 'hourFormat', '' . "\0" . 'App\\Entity\\Collaborator' . "\0" . 'hourFormatSql', '' . "\0" . 'App\\Entity\\Collaborator' . "\0" . 'activities', '' . "\0" . 'App\\Entity\\Collaborator' . "\0" . 'budgets'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Collaborator' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Collaborator' . "\0" . 'name', '' . "\0" . 'App\\Entity\\Collaborator' . "\0" . 'nif', '' . "\0" . 'App\\Entity\\Collaborator' . "\0" . 'lastSyncDate', '' . "\0" . 'App\\Entity\\Collaborator' . "\0" . 'webhookTypes', '' . "\0" . 'App\\Entity\\Collaborator' . "\0" . 'webhooks', '' . "\0" . 'App\\Entity\\Collaborator' . "\0" . 'interventions', '' . "\0" . 'App\\Entity\\Collaborator' . "\0" . 'interventionsCreated', '' . "\0" . 'App\\Entity\\Collaborator' . "\0" . 'branchOffices', '' . "\0" . 'App\\Entity\\Collaborator' . "\0" . 'collaboratorUsers', '' . "\0" . 'App\\Entity\\Collaborator' . "\0" . 'code', '' . "\0" . 'App\\Entity\\Collaborator' . "\0" . 'dateFormat', '' . "\0" . 'App\\Entity\\Collaborator' . "\0" . 'operators', '' . "\0" . 'App\\Entity\\Collaborator' . "\0" . 'cranes', '' . "\0" . 'App\\Entity\\Collaborator' . "\0" . 'email', '' . "\0" . 'App\\Entity\\Collaborator' . "\0" . 'dateFormatSql', '' . "\0" . 'App\\Entity\\Collaborator' . "\0" . 'hourFormat', '' . "\0" . 'App\\Entity\\Collaborator' . "\0" . 'hourFormatSql', '' . "\0" . 'App\\Entity\\Collaborator' . "\0" . 'activities', '' . "\0" . 'App\\Entity\\Collaborator' . "\0" . 'budgets'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Collaborator $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getName(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setName(?string $name): \App\Entity\Collaborator
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getNif(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNif', []);

        return parent::getNif();
    }

    /**
     * {@inheritDoc}
     */
    public function setNif(?string $nif): \App\Entity\Collaborator
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNif', [$nif]);

        return parent::setNif($nif);
    }

    /**
     * {@inheritDoc}
     */
    public function getLastSyncDate(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLastSyncDate', []);

        return parent::getLastSyncDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setLastSyncDate(?\DateTimeInterface $lastSyncDate): \App\Entity\Collaborator
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLastSyncDate', [$lastSyncDate]);

        return parent::setLastSyncDate($lastSyncDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getWebhookTypes(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWebhookTypes', []);

        return parent::getWebhookTypes();
    }

    /**
     * {@inheritDoc}
     */
    public function addWebhookType(\App\Entity\WebhookType $webhookType): \App\Entity\Collaborator
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addWebhookType', [$webhookType]);

        return parent::addWebhookType($webhookType);
    }

    /**
     * {@inheritDoc}
     */
    public function removeWebhookType(\App\Entity\WebhookType $webhookType): \App\Entity\Collaborator
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeWebhookType', [$webhookType]);

        return parent::removeWebhookType($webhookType);
    }

    /**
     * {@inheritDoc}
     */
    public function getWebhooks(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWebhooks', []);

        return parent::getWebhooks();
    }

    /**
     * {@inheritDoc}
     */
    public function addWebhook(\App\Entity\Webhook $webhook): \App\Entity\Collaborator
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addWebhook', [$webhook]);

        return parent::addWebhook($webhook);
    }

    /**
     * {@inheritDoc}
     */
    public function removeWebhook(\App\Entity\Webhook $webhook): \App\Entity\Collaborator
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeWebhook', [$webhook]);

        return parent::removeWebhook($webhook);
    }

    /**
     * {@inheritDoc}
     */
    public function getInterventions(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInterventions', []);

        return parent::getInterventions();
    }

    /**
     * {@inheritDoc}
     */
    public function addIntervention(\App\Entity\Intervention $intervention): \App\Entity\Collaborator
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addIntervention', [$intervention]);

        return parent::addIntervention($intervention);
    }

    /**
     * {@inheritDoc}
     */
    public function removeIntervention(\App\Entity\Intervention $intervention): \App\Entity\Collaborator
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeIntervention', [$intervention]);

        return parent::removeIntervention($intervention);
    }

    /**
     * {@inheritDoc}
     */
    public function getInterventionsCreated(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInterventionsCreated', []);

        return parent::getInterventionsCreated();
    }

    /**
     * {@inheritDoc}
     */
    public function addInterventionCreated(\App\Entity\Intervention $intervention): \App\Entity\Collaborator
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addInterventionCreated', [$intervention]);

        return parent::addInterventionCreated($intervention);
    }

    /**
     * {@inheritDoc}
     */
    public function removeInterventionCreated(\App\Entity\Intervention $intervention): \App\Entity\Collaborator
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeInterventionCreated', [$intervention]);

        return parent::removeInterventionCreated($intervention);
    }

    /**
     * {@inheritDoc}
     */
    public function getBranchOffices(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBranchOffices', []);

        return parent::getBranchOffices();
    }

    /**
     * {@inheritDoc}
     */
    public function addBranchOffice(\App\Entity\BranchOffice $branchOffice): \App\Entity\Collaborator
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addBranchOffice', [$branchOffice]);

        return parent::addBranchOffice($branchOffice);
    }

    /**
     * {@inheritDoc}
     */
    public function removeBranchOffice(\App\Entity\BranchOffice $branchOffice): \App\Entity\Collaborator
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeBranchOffice', [$branchOffice]);

        return parent::removeBranchOffice($branchOffice);
    }

    /**
     * {@inheritDoc}
     */
    public function getCollaboratorUsers(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCollaboratorUsers', []);

        return parent::getCollaboratorUsers();
    }

    /**
     * {@inheritDoc}
     */
    public function addCollaboratorUser(\App\Entity\CollaboratorUser $collaboratorUser): \App\Entity\Collaborator
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCollaboratorUser', [$collaboratorUser]);

        return parent::addCollaboratorUser($collaboratorUser);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCollaboratorUser(\App\Entity\CollaboratorUser $collaboratorUser): \App\Entity\Collaborator
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCollaboratorUser', [$collaboratorUser]);

        return parent::removeCollaboratorUser($collaboratorUser);
    }

    /**
     * {@inheritDoc}
     */
    public function addInterventionsCreated(\App\Entity\Intervention $interventionsCreated): \App\Entity\Collaborator
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addInterventionsCreated', [$interventionsCreated]);

        return parent::addInterventionsCreated($interventionsCreated);
    }

    /**
     * {@inheritDoc}
     */
    public function removeInterventionsCreated(\App\Entity\Intervention $interventionsCreated): \App\Entity\Collaborator
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeInterventionsCreated', [$interventionsCreated]);

        return parent::removeInterventionsCreated($interventionsCreated);
    }

    /**
     * {@inheritDoc}
     */
    public function getCode(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCode', []);

        return parent::getCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setCode(string $code): \App\Entity\Collaborator
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCode', [$code]);

        return parent::setCode($code);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateFormat(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateFormat', []);

        return parent::getDateFormat();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateFormat(?string $dateFormat): \App\Entity\Collaborator
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateFormat', [$dateFormat]);

        return parent::setDateFormat($dateFormat);
    }

    /**
     * {@inheritDoc}
     */
    public function getOperators(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOperators', []);

        return parent::getOperators();
    }

    /**
     * {@inheritDoc}
     */
    public function addOperator(\App\Entity\Operator $operator): \App\Entity\Collaborator
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addOperator', [$operator]);

        return parent::addOperator($operator);
    }

    /**
     * {@inheritDoc}
     */
    public function removeOperator(\App\Entity\Operator $operator): \App\Entity\Collaborator
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeOperator', [$operator]);

        return parent::removeOperator($operator);
    }

    /**
     * {@inheritDoc}
     */
    public function getCranes(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCranes', []);

        return parent::getCranes();
    }

    /**
     * {@inheritDoc}
     */
    public function addCrane(\App\Entity\Crane $crane): \App\Entity\Collaborator
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCrane', [$crane]);

        return parent::addCrane($crane);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCrane(\App\Entity\Crane $crane): \App\Entity\Collaborator
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCrane', [$crane]);

        return parent::removeCrane($crane);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', []);

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail(?string $email): \App\Entity\Collaborator
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', [$email]);

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateFormatSql(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateFormatSql', []);

        return parent::getDateFormatSql();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateFormatSql(?string $dateFormatSql): \App\Entity\Collaborator
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateFormatSql', [$dateFormatSql]);

        return parent::setDateFormatSql($dateFormatSql);
    }

    /**
     * {@inheritDoc}
     */
    public function getHourFormat(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHourFormat', []);

        return parent::getHourFormat();
    }

    /**
     * {@inheritDoc}
     */
    public function setHourFormat(?string $hourFormat): \App\Entity\Collaborator
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHourFormat', [$hourFormat]);

        return parent::setHourFormat($hourFormat);
    }

    /**
     * {@inheritDoc}
     */
    public function getHourFormatSql(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHourFormatSql', []);

        return parent::getHourFormatSql();
    }

    /**
     * {@inheritDoc}
     */
    public function setHourFormatSql(?string $HourFormatSql): \App\Entity\Collaborator
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHourFormatSql', [$HourFormatSql]);

        return parent::setHourFormatSql($HourFormatSql);
    }

    /**
     * {@inheritDoc}
     */
    public function getActivities(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActivities', []);

        return parent::getActivities();
    }

    /**
     * {@inheritDoc}
     */
    public function addActivity(\App\Entity\Activity $activity): \App\Entity\Collaborator
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addActivity', [$activity]);

        return parent::addActivity($activity);
    }

    /**
     * {@inheritDoc}
     */
    public function removeActivity(\App\Entity\Activity $activity): \App\Entity\Collaborator
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeActivity', [$activity]);

        return parent::removeActivity($activity);
    }

    /**
     * {@inheritDoc}
     */
    public function getBudgets(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBudgets', []);

        return parent::getBudgets();
    }

    /**
     * {@inheritDoc}
     */
    public function addBudget(\App\Entity\Budget $budget): \App\Entity\Collaborator
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addBudget', [$budget]);

        return parent::addBudget($budget);
    }

    /**
     * {@inheritDoc}
     */
    public function removeBudget(\App\Entity\Budget $budget): \App\Entity\Collaborator
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeBudget', [$budget]);

        return parent::removeBudget($budget);
    }

}
