<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Town extends \App\Entity\Town implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Town' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Town' . "\0" . 'name', '' . "\0" . 'App\\Entity\\Town' . "\0" . 'country', '' . "\0" . 'App\\Entity\\Town' . "\0" . 'province', '' . "\0" . 'App\\Entity\\Town' . "\0" . 'interventions', '' . "\0" . 'App\\Entity\\Town' . "\0" . 'interventionsDestination', '' . "\0" . 'App\\Entity\\Town' . "\0" . 'branchOffices', '' . "\0" . 'App\\Entity\\Town' . "\0" . 'budgets', '' . "\0" . 'App\\Entity\\Town' . "\0" . 'destinationBudgets'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Town' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Town' . "\0" . 'name', '' . "\0" . 'App\\Entity\\Town' . "\0" . 'country', '' . "\0" . 'App\\Entity\\Town' . "\0" . 'province', '' . "\0" . 'App\\Entity\\Town' . "\0" . 'interventions', '' . "\0" . 'App\\Entity\\Town' . "\0" . 'interventionsDestination', '' . "\0" . 'App\\Entity\\Town' . "\0" . 'branchOffices', '' . "\0" . 'App\\Entity\\Town' . "\0" . 'budgets', '' . "\0" . 'App\\Entity\\Town' . "\0" . 'destinationBudgets'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Town $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getName(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setName(string $name): \App\Entity\Town
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getCountry(): ?\App\Entity\Country
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCountry', []);

        return parent::getCountry();
    }

    /**
     * {@inheritDoc}
     */
    public function setCountry(?\App\Entity\Country $country): \App\Entity\Town
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCountry', [$country]);

        return parent::setCountry($country);
    }

    /**
     * {@inheritDoc}
     */
    public function getProvince(): ?\App\Entity\Province
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProvince', []);

        return parent::getProvince();
    }

    /**
     * {@inheritDoc}
     */
    public function setProvince(?\App\Entity\Province $province): \App\Entity\Town
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProvince', [$province]);

        return parent::setProvince($province);
    }

    /**
     * {@inheritDoc}
     */
    public function getInterventions(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInterventions', []);

        return parent::getInterventions();
    }

    /**
     * {@inheritDoc}
     */
    public function addIntervention(\App\Entity\Intervention $intervention): \App\Entity\Town
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addIntervention', [$intervention]);

        return parent::addIntervention($intervention);
    }

    /**
     * {@inheritDoc}
     */
    public function removeIntervention(\App\Entity\Intervention $intervention): \App\Entity\Town
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeIntervention', [$intervention]);

        return parent::removeIntervention($intervention);
    }

    /**
     * {@inheritDoc}
     */
    public function getInterventionsDestination(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInterventionsDestination', []);

        return parent::getInterventionsDestination();
    }

    /**
     * {@inheritDoc}
     */
    public function addInterventionsDestination(\App\Entity\Intervention $interventionsDestination): \App\Entity\Town
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addInterventionsDestination', [$interventionsDestination]);

        return parent::addInterventionsDestination($interventionsDestination);
    }

    /**
     * {@inheritDoc}
     */
    public function removeInterventionsDestination(\App\Entity\Intervention $interventionsDestination): \App\Entity\Town
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeInterventionsDestination', [$interventionsDestination]);

        return parent::removeInterventionsDestination($interventionsDestination);
    }

    /**
     * {@inheritDoc}
     */
    public function getBranchOffices(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBranchOffices', []);

        return parent::getBranchOffices();
    }

    /**
     * {@inheritDoc}
     */
    public function addBranchOffice(\App\Entity\BranchOffice $branchOffice): \App\Entity\Town
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addBranchOffice', [$branchOffice]);

        return parent::addBranchOffice($branchOffice);
    }

    /**
     * {@inheritDoc}
     */
    public function removeBranchOffice(\App\Entity\BranchOffice $branchOffice): \App\Entity\Town
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeBranchOffice', [$branchOffice]);

        return parent::removeBranchOffice($branchOffice);
    }

    /**
     * {@inheritDoc}
     */
    public function getBudgets(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBudgets', []);

        return parent::getBudgets();
    }

    /**
     * {@inheritDoc}
     */
    public function addBudget(\App\Entity\Budget $budget): \App\Entity\Town
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addBudget', [$budget]);

        return parent::addBudget($budget);
    }

    /**
     * {@inheritDoc}
     */
    public function removeBudget(\App\Entity\Budget $budget): \App\Entity\Town
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeBudget', [$budget]);

        return parent::removeBudget($budget);
    }

    /**
     * {@inheritDoc}
     */
    public function getDestinationBudgets(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDestinationBudgets', []);

        return parent::getDestinationBudgets();
    }

    /**
     * {@inheritDoc}
     */
    public function addDestinationBudget(\App\Entity\Budget $destinationBudget): \App\Entity\Town
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addDestinationBudget', [$destinationBudget]);

        return parent::addDestinationBudget($destinationBudget);
    }

    /**
     * {@inheritDoc}
     */
    public function removeDestinationBudget(\App\Entity\Budget $destinationBudget): \App\Entity\Town
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeDestinationBudget', [$destinationBudget]);

        return parent::removeDestinationBudget($destinationBudget);
    }

}
