<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class BranchOffice extends \App\Entity\BranchOffice implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\BranchOffice' . "\0" . 'id', '' . "\0" . 'App\\Entity\\BranchOffice' . "\0" . 'collaborator', '' . "\0" . 'App\\Entity\\BranchOffice' . "\0" . 'name', '' . "\0" . 'App\\Entity\\BranchOffice' . "\0" . 'lastSyncDate', '' . "\0" . 'App\\Entity\\BranchOffice' . "\0" . 'branchOfficeCranes', '' . "\0" . 'App\\Entity\\BranchOffice' . "\0" . 'branchOfficeOperators', '' . "\0" . 'App\\Entity\\BranchOffice' . "\0" . 'code', '' . "\0" . 'App\\Entity\\BranchOffice' . "\0" . 'zone', '' . "\0" . 'App\\Entity\\BranchOffice' . "\0" . 'telephone', '' . "\0" . 'App\\Entity\\BranchOffice' . "\0" . 'sinisterEmail', '' . "\0" . 'App\\Entity\\BranchOffice' . "\0" . 'invoicingEmail', '' . "\0" . 'App\\Entity\\BranchOffice' . "\0" . 'contactPerson', '' . "\0" . 'App\\Entity\\BranchOffice' . "\0" . 'telephone2', '' . "\0" . 'App\\Entity\\BranchOffice' . "\0" . 'telephone3', '' . "\0" . 'App\\Entity\\BranchOffice' . "\0" . 'address', '' . "\0" . 'App\\Entity\\BranchOffice' . "\0" . 'attachments', '' . "\0" . 'App\\Entity\\BranchOffice' . "\0" . 'interventions', '' . "\0" . 'App\\Entity\\BranchOffice' . "\0" . 'town', '' . "\0" . 'App\\Entity\\BranchOffice' . "\0" . 'province', '' . "\0" . 'App\\Entity\\BranchOffice' . "\0" . 'zipCode', '' . "\0" . 'App\\Entity\\BranchOffice' . "\0" . 'phones', '' . "\0" . 'App\\Entity\\BranchOffice' . "\0" . 'contacts', '' . "\0" . 'App\\Entity\\BranchOffice' . "\0" . 'branchOfficeServices', '' . "\0" . 'App\\Entity\\BranchOffice' . "\0" . 'requestCranes', '' . "\0" . 'App\\Entity\\BranchOffice' . "\0" . 'activities'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\BranchOffice' . "\0" . 'id', '' . "\0" . 'App\\Entity\\BranchOffice' . "\0" . 'collaborator', '' . "\0" . 'App\\Entity\\BranchOffice' . "\0" . 'name', '' . "\0" . 'App\\Entity\\BranchOffice' . "\0" . 'lastSyncDate', '' . "\0" . 'App\\Entity\\BranchOffice' . "\0" . 'branchOfficeCranes', '' . "\0" . 'App\\Entity\\BranchOffice' . "\0" . 'branchOfficeOperators', '' . "\0" . 'App\\Entity\\BranchOffice' . "\0" . 'code', '' . "\0" . 'App\\Entity\\BranchOffice' . "\0" . 'zone', '' . "\0" . 'App\\Entity\\BranchOffice' . "\0" . 'telephone', '' . "\0" . 'App\\Entity\\BranchOffice' . "\0" . 'sinisterEmail', '' . "\0" . 'App\\Entity\\BranchOffice' . "\0" . 'invoicingEmail', '' . "\0" . 'App\\Entity\\BranchOffice' . "\0" . 'contactPerson', '' . "\0" . 'App\\Entity\\BranchOffice' . "\0" . 'telephone2', '' . "\0" . 'App\\Entity\\BranchOffice' . "\0" . 'telephone3', '' . "\0" . 'App\\Entity\\BranchOffice' . "\0" . 'address', '' . "\0" . 'App\\Entity\\BranchOffice' . "\0" . 'attachments', '' . "\0" . 'App\\Entity\\BranchOffice' . "\0" . 'interventions', '' . "\0" . 'App\\Entity\\BranchOffice' . "\0" . 'town', '' . "\0" . 'App\\Entity\\BranchOffice' . "\0" . 'province', '' . "\0" . 'App\\Entity\\BranchOffice' . "\0" . 'zipCode', '' . "\0" . 'App\\Entity\\BranchOffice' . "\0" . 'phones', '' . "\0" . 'App\\Entity\\BranchOffice' . "\0" . 'contacts', '' . "\0" . 'App\\Entity\\BranchOffice' . "\0" . 'branchOfficeServices', '' . "\0" . 'App\\Entity\\BranchOffice' . "\0" . 'requestCranes', '' . "\0" . 'App\\Entity\\BranchOffice' . "\0" . 'activities'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (BranchOffice $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getCollaborator(): ?\App\Entity\Collaborator
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCollaborator', []);

        return parent::getCollaborator();
    }

    /**
     * {@inheritDoc}
     */
    public function setCollaborator(?\App\Entity\Collaborator $collaborator): \App\Entity\BranchOffice
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCollaborator', [$collaborator]);

        return parent::setCollaborator($collaborator);
    }

    /**
     * {@inheritDoc}
     */
    public function getName(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setName(string $name): \App\Entity\BranchOffice
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getLastSyncDate(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLastSyncDate', []);

        return parent::getLastSyncDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setLastSyncDate(\DateTimeInterface $lastSyncDate): \App\Entity\BranchOffice
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLastSyncDate', [$lastSyncDate]);

        return parent::setLastSyncDate($lastSyncDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getBranchOfficeCranes(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBranchOfficeCranes', []);

        return parent::getBranchOfficeCranes();
    }

    /**
     * {@inheritDoc}
     */
    public function addBranchOfficeCrane(\App\Entity\BranchOfficeCrane $branchOfficeCrane): \App\Entity\BranchOffice
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addBranchOfficeCrane', [$branchOfficeCrane]);

        return parent::addBranchOfficeCrane($branchOfficeCrane);
    }

    /**
     * {@inheritDoc}
     */
    public function removeBranchOfficeCrane(\App\Entity\BranchOfficeCrane $branchOfficeCrane): \App\Entity\BranchOffice
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeBranchOfficeCrane', [$branchOfficeCrane]);

        return parent::removeBranchOfficeCrane($branchOfficeCrane);
    }

    /**
     * {@inheritDoc}
     */
    public function getBranchOfficeOperators(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBranchOfficeOperators', []);

        return parent::getBranchOfficeOperators();
    }

    /**
     * {@inheritDoc}
     */
    public function addBranchOfficeOperator(\App\Entity\BranchOfficeOperator $branchOfficeOperator): \App\Entity\BranchOffice
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addBranchOfficeOperator', [$branchOfficeOperator]);

        return parent::addBranchOfficeOperator($branchOfficeOperator);
    }

    /**
     * {@inheritDoc}
     */
    public function removeBranchOfficeOperator(\App\Entity\BranchOfficeOperator $branchOfficeOperator): \App\Entity\BranchOffice
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeBranchOfficeOperator', [$branchOfficeOperator]);

        return parent::removeBranchOfficeOperator($branchOfficeOperator);
    }

    /**
     * {@inheritDoc}
     */
    public function getCode(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCode', []);

        return parent::getCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setCode(string $code): \App\Entity\BranchOffice
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCode', [$code]);

        return parent::setCode($code);
    }

    /**
     * {@inheritDoc}
     */
    public function getZone(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getZone', []);

        return parent::getZone();
    }

    /**
     * {@inheritDoc}
     */
    public function setZone(?string $zone): \App\Entity\BranchOffice
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setZone', [$zone]);

        return parent::setZone($zone);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelephone(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelephone', []);

        return parent::getTelephone();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelephone(string $telephone): \App\Entity\BranchOffice
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelephone', [$telephone]);

        return parent::setTelephone($telephone);
    }

    /**
     * {@inheritDoc}
     */
    public function getSinisterEmail(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSinisterEmail', []);

        return parent::getSinisterEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setSinisterEmail(string $sinisterEmail): \App\Entity\BranchOffice
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSinisterEmail', [$sinisterEmail]);

        return parent::setSinisterEmail($sinisterEmail);
    }

    /**
     * {@inheritDoc}
     */
    public function getInvoicingEmail(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInvoicingEmail', []);

        return parent::getInvoicingEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setInvoicingEmail(string $invoicingEmail): \App\Entity\BranchOffice
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInvoicingEmail', [$invoicingEmail]);

        return parent::setInvoicingEmail($invoicingEmail);
    }

    /**
     * {@inheritDoc}
     */
    public function getContactPerson(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContactPerson', []);

        return parent::getContactPerson();
    }

    /**
     * {@inheritDoc}
     */
    public function setContactPerson(string $contactPerson): \App\Entity\BranchOffice
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContactPerson', [$contactPerson]);

        return parent::setContactPerson($contactPerson);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelephone2(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelephone2', []);

        return parent::getTelephone2();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelephone2(?string $telephone2): \App\Entity\BranchOffice
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelephone2', [$telephone2]);

        return parent::setTelephone2($telephone2);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelephone3(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelephone3', []);

        return parent::getTelephone3();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelephone3(?string $telephone3): \App\Entity\BranchOffice
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelephone3', [$telephone3]);

        return parent::setTelephone3($telephone3);
    }

    /**
     * {@inheritDoc}
     */
    public function getAddress(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAddress', []);

        return parent::getAddress();
    }

    /**
     * {@inheritDoc}
     */
    public function setAddress(?string $address): \App\Entity\BranchOffice
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAddress', [$address]);

        return parent::setAddress($address);
    }

    /**
     * {@inheritDoc}
     */
    public function getAttachments(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAttachments', []);

        return parent::getAttachments();
    }

    /**
     * {@inheritDoc}
     */
    public function addAttachment(\App\Entity\Attachment $attachment): \App\Entity\BranchOffice
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addAttachment', [$attachment]);

        return parent::addAttachment($attachment);
    }

    /**
     * {@inheritDoc}
     */
    public function removeAttachment(\App\Entity\Attachment $attachment): \App\Entity\BranchOffice
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeAttachment', [$attachment]);

        return parent::removeAttachment($attachment);
    }

    /**
     * {@inheritDoc}
     */
    public function getInterventions(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInterventions', []);

        return parent::getInterventions();
    }

    /**
     * {@inheritDoc}
     */
    public function addIntervention(\App\Entity\Intervention $intervention): \App\Entity\BranchOffice
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addIntervention', [$intervention]);

        return parent::addIntervention($intervention);
    }

    /**
     * {@inheritDoc}
     */
    public function removeIntervention(\App\Entity\Intervention $intervention): \App\Entity\BranchOffice
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeIntervention', [$intervention]);

        return parent::removeIntervention($intervention);
    }

    /**
     * {@inheritDoc}
     */
    public function getTown(): ?\App\Entity\Town
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTown', []);

        return parent::getTown();
    }

    /**
     * {@inheritDoc}
     */
    public function setTown(?\App\Entity\Town $town): \App\Entity\BranchOffice
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTown', [$town]);

        return parent::setTown($town);
    }

    /**
     * {@inheritDoc}
     */
    public function getProvince(): ?\App\Entity\Province
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProvince', []);

        return parent::getProvince();
    }

    /**
     * {@inheritDoc}
     */
    public function setProvince(?\App\Entity\Province $province): \App\Entity\BranchOffice
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProvince', [$province]);

        return parent::setProvince($province);
    }

    /**
     * {@inheritDoc}
     */
    public function getZipCode(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getZipCode', []);

        return parent::getZipCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setZipCode(?string $zipCode): \App\Entity\BranchOffice
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setZipCode', [$zipCode]);

        return parent::setZipCode($zipCode);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhones(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhones', []);

        return parent::getPhones();
    }

    /**
     * {@inheritDoc}
     */
    public function addPhone(\App\Entity\Phone $phone): \App\Entity\BranchOffice
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPhone', [$phone]);

        return parent::addPhone($phone);
    }

    /**
     * {@inheritDoc}
     */
    public function removePhone(\App\Entity\Phone $phone): \App\Entity\BranchOffice
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removePhone', [$phone]);

        return parent::removePhone($phone);
    }

    /**
     * {@inheritDoc}
     */
    public function getContacts(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContacts', []);

        return parent::getContacts();
    }

    /**
     * {@inheritDoc}
     */
    public function addContact(\App\Entity\Contact $contact): \App\Entity\BranchOffice
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addContact', [$contact]);

        return parent::addContact($contact);
    }

    /**
     * {@inheritDoc}
     */
    public function removeContact(\App\Entity\Contact $contact): \App\Entity\BranchOffice
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeContact', [$contact]);

        return parent::removeContact($contact);
    }

    /**
     * {@inheritDoc}
     */
    public function getBranchOfficeServices(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBranchOfficeServices', []);

        return parent::getBranchOfficeServices();
    }

    /**
     * {@inheritDoc}
     */
    public function addBranchOfficeService(\App\Entity\BranchOfficeService $branchOfficeService): \App\Entity\BranchOffice
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addBranchOfficeService', [$branchOfficeService]);

        return parent::addBranchOfficeService($branchOfficeService);
    }

    /**
     * {@inheritDoc}
     */
    public function removeBranchOfficeService(\App\Entity\BranchOfficeService $branchOfficeService): \App\Entity\BranchOffice
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeBranchOfficeService', [$branchOfficeService]);

        return parent::removeBranchOfficeService($branchOfficeService);
    }

    /**
     * {@inheritDoc}
     */
    public function getRequestCranes(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRequestCranes', []);

        return parent::getRequestCranes();
    }

    /**
     * {@inheritDoc}
     */
    public function addRequestCrane(\App\Entity\RequestCrane $requestCrane): \App\Entity\BranchOffice
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addRequestCrane', [$requestCrane]);

        return parent::addRequestCrane($requestCrane);
    }

    /**
     * {@inheritDoc}
     */
    public function removeRequestCrane(\App\Entity\RequestCrane $requestCrane): \App\Entity\BranchOffice
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeRequestCrane', [$requestCrane]);

        return parent::removeRequestCrane($requestCrane);
    }

    /**
     * {@inheritDoc}
     */
    public function getActivities(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActivities', []);

        return parent::getActivities();
    }

    /**
     * {@inheritDoc}
     */
    public function addActivity(\App\Entity\Activity $activity): \App\Entity\BranchOffice
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addActivity', [$activity]);

        return parent::addActivity($activity);
    }

    /**
     * {@inheritDoc}
     */
    public function removeActivity(\App\Entity\Activity $activity): \App\Entity\BranchOffice
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeActivity', [$activity]);

        return parent::removeActivity($activity);
    }

}
