<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class VhType extends \App\Entity\VhType implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\VhType' . "\0" . 'id', '' . "\0" . 'App\\Entity\\VhType' . "\0" . 'name', '' . "\0" . 'App\\Entity\\VhType' . "\0" . 'vhModels', '' . "\0" . 'App\\Entity\\VhType' . "\0" . 'interventions', '' . "\0" . 'App\\Entity\\VhType' . "\0" . 'code', '' . "\0" . 'App\\Entity\\VhType' . "\0" . 'vehicleType', '' . "\0" . 'App\\Entity\\VhType' . "\0" . 'vhSectionParts'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\VhType' . "\0" . 'id', '' . "\0" . 'App\\Entity\\VhType' . "\0" . 'name', '' . "\0" . 'App\\Entity\\VhType' . "\0" . 'vhModels', '' . "\0" . 'App\\Entity\\VhType' . "\0" . 'interventions', '' . "\0" . 'App\\Entity\\VhType' . "\0" . 'code', '' . "\0" . 'App\\Entity\\VhType' . "\0" . 'vehicleType', '' . "\0" . 'App\\Entity\\VhType' . "\0" . 'vhSectionParts'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (VhType $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getName(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setName(string $name): \App\Entity\VhType
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getVhModels(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVhModels', []);

        return parent::getVhModels();
    }

    /**
     * {@inheritDoc}
     */
    public function addVhModel(\App\Entity\VhModel $vhModel): \App\Entity\VhType
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addVhModel', [$vhModel]);

        return parent::addVhModel($vhModel);
    }

    /**
     * {@inheritDoc}
     */
    public function removeVhModel(\App\Entity\VhModel $vhModel): \App\Entity\VhType
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeVhModel', [$vhModel]);

        return parent::removeVhModel($vhModel);
    }

    /**
     * {@inheritDoc}
     */
    public function getInterventions(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInterventions', []);

        return parent::getInterventions();
    }

    /**
     * {@inheritDoc}
     */
    public function addIntervention(\App\Entity\Intervention $intervention): \App\Entity\VhType
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addIntervention', [$intervention]);

        return parent::addIntervention($intervention);
    }

    /**
     * {@inheritDoc}
     */
    public function removeIntervention(\App\Entity\Intervention $intervention): \App\Entity\VhType
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeIntervention', [$intervention]);

        return parent::removeIntervention($intervention);
    }

    /**
     * {@inheritDoc}
     */
    public function getCode(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCode', []);

        return parent::getCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setCode(string $code): \App\Entity\VhType
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCode', [$code]);

        return parent::setCode($code);
    }

    /**
     * {@inheritDoc}
     */
    public function getVehicleType(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVehicleType', []);

        return parent::getVehicleType();
    }

    /**
     * {@inheritDoc}
     */
    public function setVehicleType(string $vehicleType): \App\Entity\VhType
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVehicleType', [$vehicleType]);

        return parent::setVehicleType($vehicleType);
    }

    /**
     * {@inheritDoc}
     */
    public function getVhSectionParts(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVhSectionParts', []);

        return parent::getVhSectionParts();
    }

    /**
     * {@inheritDoc}
     */
    public function addVhSectionPart(\App\Entity\VhSectionPart $vhSectionPart): \App\Entity\VhType
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addVhSectionPart', [$vhSectionPart]);

        return parent::addVhSectionPart($vhSectionPart);
    }

    /**
     * {@inheritDoc}
     */
    public function removeVhSectionPart(\App\Entity\VhSectionPart $vhSectionPart): \App\Entity\VhType
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeVhSectionPart', [$vhSectionPart]);

        return parent::removeVhSectionPart($vhSectionPart);
    }

}
