<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNs24mO9\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNs24mO9/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNs24mO9.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNs24mO9\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerNs24mO9\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Ns24mO9',
    'container.build_id' => '3572674a',
    'container.build_time' => 1615985791,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNs24mO9');
